# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Andrei Mîță
tagline:          'Pagină personală'
description:      'Toatel lucrurile într-un singur loc: analize, rapoarte, articole, cod.'
url:              https://andreimita.github.io
baseurl:          /

author:
  name:           'Andrei Mîță'
  url:            https://twitter.com/pisiconline

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
